[package]
name = "chainreaction"
version = "0.0.1"
authors = ["vypxl <thomas@vypxl.io>"]
description = ""
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
